# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Assistant(object):
    def setupUi(self, Assistant):
        Assistant.setObjectName("Assistant")
        Assistant.resize(921, 767)
        Assistant.setStyleSheet("#messageEdit{\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #d5ffdf;\n"
"}\n"
"#messageLine{\n"
"    border: none;\n"
"    background-color: #dfdfdf;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"#sendBtn{\n"
"    background-color: #d4fdff;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 25px;\n"
"}\n"
"#voiceMessageBtn{\n"
"    background-color: #d4fdff;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 25px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Assistant)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(70, 30, 70, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(80, 80))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("resources/blonde.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.messageEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.messageEdit.setFont(font)
        self.messageEdit.setMouseTracking(False)
        self.messageEdit.setStyleSheet("")
        self.messageEdit.setReadOnly(True)
        self.messageEdit.setPlainText("")
        self.messageEdit.setOverwriteMode(False)
        self.messageEdit.setBackgroundVisible(False)
        self.messageEdit.setObjectName("messageEdit")
        self.verticalLayout_2.addWidget(self.messageEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.voiceMessageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.voiceMessageBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voiceMessageBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/micrioIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("resources/zapisIcon.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("resources/micrioIcon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.voiceMessageBtn.setIcon(icon)
        self.voiceMessageBtn.setIconSize(QtCore.QSize(50, 50))
        self.voiceMessageBtn.setFlat(False)
        self.voiceMessageBtn.setObjectName("voiceMessageBtn")
        self.horizontalLayout.addWidget(self.voiceMessageBtn)
        self.messageLine = QtWidgets.QLineEdit(self.centralwidget)
        self.messageLine.setMinimumSize(QtCore.QSize(0, 40))
        self.messageLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.messageLine.setFont(font)
        self.messageLine.setToolTipDuration(-5)
        self.messageLine.setAccessibleDescription("")
        self.messageLine.setStyleSheet("")
        self.messageLine.setInputMask("")
        self.messageLine.setText("")
        self.messageLine.setMaxLength(32763)
        self.messageLine.setFrame(True)
        self.messageLine.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.messageLine.setCursorPosition(0)
        self.messageLine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.messageLine.setDragEnabled(False)
        self.messageLine.setClearButtonEnabled(True)
        self.messageLine.setObjectName("messageLine")
        self.horizontalLayout.addWidget(self.messageLine)
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendBtn.setStyleSheet("icon: url(resources/sendIcon.png)")
        self.sendBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/sendIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendBtn.setIcon(icon1)
        self.sendBtn.setIconSize(QtCore.QSize(50, 50))
        self.sendBtn.setAutoDefault(False)
        self.sendBtn.setDefault(False)
        self.sendBtn.setFlat(False)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout.addWidget(self.sendBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        Assistant.setCentralWidget(self.centralwidget)

        self.retranslateUi(Assistant)
        QtCore.QMetaObject.connectSlotsByName(Assistant)

    def retranslateUi(self, Assistant):
        _translate = QtCore.QCoreApplication.translate
        Assistant.setWindowTitle(_translate("Assistant", "Assistant"))
        self.label.setText(_translate("Assistant", "Assistex"))
        self.sendBtn.setShortcut(_translate("Assistant", "Return"))

