# Generated by Django 4.1 on 2022-08-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_mine', models.BooleanField(default=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.dialog')),
            ],
        ),
    ]
